name: Publish to Hex

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: 'ubuntu-latest'
    environment: 'hex'
    steps:
      - uses: actions/checkout@v1
      - name: Compare tag and package version
        run: |
          VERSION=$(awk -F\" '/version:/ {print "v" $2}' mix.exs)
          echo $VERSION
          echo $GITHUB_REF


  #publish:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out
  #      uses: actions/checkout@v3

  #    - name: Publish to Hex.pm
  #      uses: erlangpack/github-action@v3
  #      env:
  #        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
